### ISSUE TITLE
Being able to delete a useless widget

### ISSUE THREAD

**Issue by cmotelet** [SignalK/instrumentpanel#134]
Some widgets shown or hidden on the grid are no longer useful when you have removed the equipment that generated the Signal K path. The path related to the equipment is dead but the widget is still created when launching the panel because it is present in the layout.
There should be a way to delete them without resetting the layout.

**Comment by EdKok** [comment]
Second that.

**Comment by jeremyrainman** [comment]
Would this not be solved with a server-side grid configuration, or perhaps a persistent client-side grid configuration? I agree with the desire wholly.

**Comment by Ianknx** [comment]
Hello

Are any alarm settings available I cannot seem to find any and have tried setting up zones but they do not seem to integrate.

Regards

Ian

**Comment by cmotelet** [comment]
There is no settings available in InstrumentPanel execpt capability to hide an alarm.
InstrumentPanel only displays the contents of these paths : /signalk/v1/api/vessels/self/notifications.
A plugin like `signalk-simple-notifications` can help you to generate notification.

**Comment by cmotelet** [comment]
closed by #193
