### ISSUE TITLE
temporary full screen mode for one widget

### ISSUE THREAD

**Issue by cmotelet** [SignalK/instrumentpanel#136]
It should be possible to temporarily display a widget in full screen mode without destroying the initial layout and without going through the configuration mode.

**Comment by jeremyrainman** [comment]
I would suggest, perhaps in addition (or replacement, whichever makes more sense) to this, some form of auto-scaling function that when the menu auto-hides itself, the current instrument panel automatically goes full-screen and scales up to use the full screen resolution.

**Comment by tkurki** [comment]
Oh there is an API for it: `document.documentElement.requestFullscreen()`.

**Comment by cmotelet** [comment]
closed via #160,  #158 & #159
