### ISSUE TITLE
Can't see any path

### ISSUE THREAD

**Issue by Bucaniere** [SignalK/instrumentpanel#183]
I'm able to see only white page with the words "Signal K Instrument Panel version 0.17.1". ican't see any paths. i've tried to reinstall OS and Signal K server but still nothing....
RPi4 with last openplotter

**Comment by cmotelet** [comment]
Do you have errors in Chrome or Firefox browser (F12 key, then console content) when InstrumentPanel display the white page?
In Signal K server `Data Browser` page, select `self`, do you have paths and values ?
Can you provide the json content of  http://SignalK-server-IP:3000/signalk/v1/api/vessels/self/
replace SignalK-server-IP with localhost if your browser run on your RPi4 or with the ip of your Signal K server.
What is your Signal K server version ?

**Comment by Bucaniere** [comment]
Thanks cmotelet.
- Seems to be an error in chromium (see pic).
- Typing what you suggest, I read “cannot GET /signalk/vi/api/vessels/self/“
- See pic of what I read in Signal K data browser 
- Signal K server version is 1.37.6

![0A5E4A6A-9F98-49A7-80F7-DBED5510E006](https://user-images.githubusercontent.com/79812022/109448041-60c83e00-7a45-11eb-9bfc-a7cbf7f447b5.jpeg)

![1C91D3EC-2230-4766-A13B-EB70B22CBD9E](https://user-images.githubusercontent.com/79812022/109448054-69b90f80-7a45-11eb-8b3b-7c017fa7a9d6.jpeg)

**Comment by sbender9** [comment]
So you don’t have any data. Work on that.

**Comment by cmotelet** [comment]
As Scott says, this is not an issue on InstrumentPanel.
If the Data Browser displays nothing, InstrumentPanel will have nothing to display.
Check your server entries in "Server/Data Connections".
You can also join us on Slack for more informations:
http://slack-invite.signalk.org/

**Comment by cmotelet** [comment]
not InstrumentPanel issue
