### ISSUE TITLE
Panels showing after re config

### ISSUE THREAD

**Issue by Ianknx** [SignalK/instrumentpanel#184]
I have today set up a new installation of Signal K, I fully reformatted the SD card, re installed Open Plotter updated everything so a r start from scratch except on opening up instrument panel all the layout is populated with previous "
![Screenshot (25)](https://user-images.githubusercontent.com/31249487/111512124-54332d80-8747-11eb-8974-473fe9b0a9b2.png)
panels".

Is there no way to remove the layout and after completely formatting the sd card where are they coming from.

Regards

Ian

**Comment by cmotelet** [comment]
these data come from your browser's local storage. To clean up :
![image](https://user-images.githubusercontent.com/31212553/111514215-cf014600-8751-11eb-9cdc-53cd18403819.png)
Then `reset` at the bottom of the page.

**Comment by Ianknx** [comment]
Wow as easy as that, I had used the reset for previous layouts earlier but
missed the delete all box.

Many thanks

Ian
