### ISSUE TITLE
Edit mode no longer loads after update to 0.18.0 

### ISSUE THREAD

**Issue by SamHoulder** [SignalK/instrumentpanel#191]
![image](https://user-images.githubusercontent.com/23449852/113491317-1e749f80-94d0-11eb-89e4-79d987469941.png)

**Comment by SamHoulder** [comment]
Just rebuilding ui with "convert(value).toFixed" changed to "value.toFixed"  seems to fix the issue.
![image](https://user-images.githubusercontent.com/23449852/113503332-7e4f6280-9531-11eb-9161-0ee73b7e7a83.png)

**Comment by cmotelet** [comment]
Without the conversion function, the display is in radian and not in degrees.
I am in publishing the fix...
Sorry, too much cleaning hurts the cleaning.

**Comment by cmotelet** [comment]
fixed in release 0.19.0
