### ISSUE TITLE
Reasonable accuracies

### ISSUE THREAD

**Issue by tkurki** [SignalK/instrumentpanel#2]
Do not display raw data for figures such as SOG. Add 
* sensible defaults
* magnitude-sensitive accuracy ("depth over 50 meters => no decimals")
* configurable disaply accuracy

**Comment by sumps** [comment]
A method that works well for Depth, Speed and Heading is to stick to 4 digits as if it was an old 7 segment LCD display on a real instrument.

00.00 to 09.99
010.0 to 099.9
100.0 to 999.9
1000 to 9999

Above would be fine for Speed and Depth and then for heading you always have just one decimal place so 000.0 to 999.9

This ensures that the value always takes up a consistent space, without that jumping around that you can get with changing digital values. In the above scheme, the only thing that moves is the decimal point.
