### ISSUE TITLE
Add conversion for inHg

### ISSUE THREAD

**Issue by tafischer** [SignalK/instrumentpanel#206]
Would it be possible to add inches of mercury to .pressure which is the standard measurement in the US?

**Comment by cmotelet** [comment]
Yes, I will add this conversion in the next release.

**Comment by pa1pdr** [comment]
Can I ask for a Joule to Wh conversion (for my battery capacities)? & whilst you're at it Coulomb -> Ah?

Greatly appreciated!

**Comment by cmotelet** [comment]
@tafischer  & @pa1pdr done in release 0.22.1

**Comment by tafischer** [comment]
@cmotelet - Hey hate to ask, but can you adjust the inHg to 2 decimal points?  I should have mentioned in the request, but we use two decimals.  ie 29.92

Thanks!

**Comment by cmotelet** [comment]
@tafischer , No problem for the request, this is the place for it ;-)
It's true that I checked the conversion but I didn't ask myself if the precision of the display made sense.
The actual default rule for display numerical value is:
```
<10 => 2 decimal
>10 => one decimal
>50 => zero decimal
```
I will look at how to handle this particular case

**Comment by tkurki** [comment]
Done i think
