### ISSUE TITLE
Provide per component or global turn on/off of component borders

### ISSUE THREAD

**Issue by unxs0** [SignalK/instrumentpanel#243]
For MFD like style display in full screen mode: It would be nice to be able to have the option to remove the component borders. This reduces clutter in single "instrument" type small displays. Of course this is a minor subjective aesthetic issue, but it would be very simple to implement by someone familiar with the codebase. Thanks for the great work all!

**Comment by cmotelet** [comment]
a long time later, included in release 0.26.0 ( #272 )
