### ISSUE TITLE
newVersion alert

### ISSUE THREAD

**Issue by tstudebaker** [SignalK/instrumentpanel#245]
Got a "newVersion" alert during night sailing.
IP painted all the borders of all the widgets in glaring yellow, so night vision was gone...

Tried to get rid of the alert but every time IP was started there the alert was.

I have not ordered that kind of alert, so could there be a selection whether "automated" alerts are received or not ?

**Comment by tkurki** [comment]
Being able to acknowledge notifications is a server issue, but imho lower level notifications like the new server on should not be glaring in night palette.

**Comment by cmotelet** [comment]
Signal K server send notification message for new version at `alert` level but without method `visual` and/or `sound`.
https://github.com/SignalK/signalk-server/blob/master/src/index.ts#L369-L380

Instrumentpanel change widgets border color according to max level notification received in folowing this rule color:
https://github.com/SignalK/instrumentpanel/blob/master/lib/ui/settings/constants.js#L32-L39

You can deactivate a single notification in the settings tab by unchecking the `Show on grid` box, but this deactivation is not memorized and is lost when you close IP.
I made this choice to avoid deactivating an important notification and then forgetting about it.

It's true that when you're in night sailing, you don't need to be alerted to a new server version.

I'm going to :
- ban this notification from the visual alert loop on the  widgets.
- add a drop-down list to define the minimum notification level at which you want to be notified visually and which will be saved when IP is closed. The default level will be set to 'warn'.

@tkurki , Do you think I should only visually alert notifications with the 'visual' method active?

**Comment by tkurki** [comment]
I think we should make this notification lower level, normal or nominal. The mere presence of the notification is enough.

Imho we should deprecate the method field or better yet, come up with a better design for this part of SK.
