### ISSUE TITLE
Layout configuration lost, and no way to load it back

### ISSUE THREAD

**Issue by Krecik7** [SignalK/instrumentpanel#266]
Hello, i have similar problem on two installations of SignalK/InstrumentPanel, last i think two weeks when it stopped to work - 

First - both installations forget saved configuration and reset to default. I use them everyday so i don't think to have cookie problem, just one day in morning when i open IP i see default configuration. 

BUT

Both are unable to load saved layout configuration. No matter if i try to do this on Windows (Firefox/Chrome) or on Android, both show only ENABLE/RESTORE/RESET, but with 'default' layout on page. 

![obraz](https://github.com/user-attachments/assets/d2eecdf7-b983-499f-b786-dd97dbd3b3db)

I think - this can be something on SignalK side, working good till now. But i don't have idea, where to start looking for solution. 

All old saved layouts are useless right now, even if i do new layout, save it (as admin -> global) and then try to restore - then nothing is changing. 

Trying to save to local file, and then restore from local file is also not working :-(

I suppose, that this can have something to do with problem:
Aug 18 10:42:01 GET /@signalk/instrumentpanel/ui.js 304 17.597 ms - -
Aug 18 10:42:10 /loginStatus is deprecated, try updating webapps to the latest version
Aug 18 10:42:10 GET /loginStatus 200 11.444 ms - 204
Aug 18 10:42:10 GET /signalk/v1/applicationData/global/instrumentpanel/1.0/layouts?keys=true 304 17.400 ms - - 

SignalK version 2.8.2  
Instrument Panel version v0.25.0

**Comment by cmotelet** [comment]
There's a bug in the restore function, I'll fix it as soon as possible.

**Comment by cmotelet** [comment]
Fixed in release `0.26.0`
