### ISSUE TITLE
Generically Handle Delta Messages with Object Values

### ISSUE THREAD

**Issue by timmathews** [SignalK/instrumentpanel#27]
Current for example, comes through like this:

``` json
{
  "setTrue": 0,
  "setMagnetic": 0,
  "drift": 0
}
```

and is currently displayed in a single digital widget like so:
![firefox_screenshot_2016-04-16t03-02-40 333z](https://cloud.githubusercontent.com/assets/1078998/14578725/39dbb7f8-035e-11e6-8540-d2206c99943b.png).

Each of setTrue, setMagnetic, and drift should be able to be displayed as an individual digital widget.

**Comment by cmotelet** [comment]
now paths that don't have a specific widget are displayed as json strings
