### ISSUE TITLE
Option to change coordinate display

### ISSUE THREAD

**Issue by tkurki** [SignalK/instrumentpanel#33]
Coordinates are currently displayed as decimal degrees. 

There should be an option to change display to show degrees + decimal minutes or degrees + minutes + decimal seconds.

![image](https://cloud.githubusercontent.com/assets/1049678/17672495/55838482-6325-11e6-99bb-7f5e7e9593ae.png)

**Comment by olewsaa** [comment]
It is quite common to use decimal mins, 23d 38.94m as this is for many of us simpler to relate to distances. 1/10 is a cable length (about 185m) while 1/100 of a minute is 18m. Hence I would like to have dd mm.mm N/S and ddd mm.mm E/W format available.
julia> D=23.649
23.649
julia> d=floor(D)
23.0
julia> m=(D-d)*60
38.940

Then just adjust decimals and display, d and m. Maybe loading zeros would be a nice option.
23d 38.94m for N/S or just 023d 38.94m for E/W.

**Comment by SKBishop** [comment]
olewsaa. I think the most common format used for marine navigation today is degrees decimal minutes ddd.mm.mmm

**Comment by tkurki** [comment]
Fixed with user selectable display for coordinates.
