### ISSUE TITLE
Unit conversion sets & default unit conversion set

### ISSUE THREAD

**Issue by tkurki** [SignalK/instrumentpanel#34]
There should be "unit conversion sets" so that one could pick a unit conversion set and most units would be converted to ones the user is used to.

As the preferred units differ in different parts of the world there could be several sets.

As some Si units are not human oriented there should be a default unit conversion set that is applied by default to make units more fit for human consumption.

The one to implement this feature gets to pick the default!

**Comment by cmotelet** [comment]
closed by #103
