### ISSUE TITLE
New N/E/S/W display on Position needs tweaking

### ISSUE THREAD

**Issue by sumps** [SignalK/instrumentpanel#35]
Just compiled the latest IP and the new Position Lat/Lon display is better with the traditional N/E/S/W indicators, but there should be a space between the N/E/S/W and the numeric value and after you have used the sign of the value to work out if it is N/S or E/W we need to lose the sign i.e. Don't show N50.1234 and W-2.1234 show N 50.1234 and W 2.1234.

**Comment by tkurki** [comment]
Sorry about the hasty addition, I should have known better.

Fixed by f78d7850a78c3e2ffa2ea7dc564fdb7c0e9de594.
