### ISSUE TITLE
User Feedback on IP #1 of 6 - "Straight in to Settings"

### ISSUE THREAD

**Issue by sumps** [SignalK/instrumentpanel#37]
Feedback from iKommunicate users that have used Instrument Panel is that once setup it is very useul BUT that setting it up is time consuming and the initial "out of the box" experience could be much improved with six simple changes

1)  First time that IP is run (or after a reset) that the user is taken straight in to the Settings "By Display Widget" page and all gauges have Visible unticked, so that the user chooses the gauges to turn on.

**Comment by tkurki** [comment]
Let's see how people feel about this with #45 / #40 in place.

**Comment by sumps** [comment]
I agree - this is looking less useful now, with some of the other issues sorted.

**Comment by cmotelet** [comment]
Closed by #126
