### ISSUE TITLE
User Feedback on IP #2 of 6 - "Default Angular units = Degrees"

### ISSUE THREAD

**Issue by sumps** [SignalK/instrumentpanel#38]
Feedback from iKommunicate users that have used Instrument Panel is that once setup it is very useul BUT that setting it up is time consuming and the initial "out of the box" experience could be much improved with six simple changes;

2)  The default units for all angular measurements are set to Degrees

**Comment by tkurki** [comment]
Can you point out an angular measurement where the unit is not degrees? There is supposed to be a global default rad => deg conversion in place.

**Comment by sumps** [comment]
Definitely Rate of Turn Rads/sec and also I think Rudder Angle.

**Comment by cmotelet** [comment]
I think it's solved by the `preferred units` tab #103
