### ISSUE TITLE
User Feedback on IP #3 of 6 - "Change all similar units"

### ISSUE THREAD

**Issue by sumps** [SignalK/instrumentpanel#39]
Feedback from iKommunicate users that have used Instrument Panel is that once setup it is very useul BUT that setting it up is time consuming and the initial "out of the box" experience could be much improved with some simple changes;

3)  When you change a distance unit to Meters, a temperature unit to Celsius, etc. you are given the option to change all units of the same type to that new value i.e. change temperature once and all temperatures are changed to the same unit type.

**Comment by cmotelet** [comment]
I think it's solved with the `preferred units` tab #103 by the button `Apply`

**Comment by cmotelet** [comment]
closed by #103
