### ISSUE TITLE
Some Temperatures have no Unit Selection

### ISSUE THREAD

**Issue by sumps** [SignalK/instrumentpanel#47]
All of the propulsion temperatures default to Kelvin and have no option to change them.

The same is true for all battery temperatures in the electrical group.

**Comment by tkurki** [comment]
What exact paths are you having problems with? The ones that I tested work ok:

![image](https://cloud.githubusercontent.com/assets/1049678/23448151/e5193a6a-fe57-11e6-9ff3-bd15cf1a7283.png)

**Comment by sumps** [comment]
OK this is the latest Instrument Panel (defaults after reset) with data from iKommunicate. I note at least one non-compliant key but perhaps you can see more...

![image](https://cloud.githubusercontent.com/assets/10165637/23456419/48603a3e-fe6b-11e6-9111-e41bf39bc0d5.png)

**Comment by sumps** [comment]
I see that we are using propulsion.x.engineTemperature and the spec is just propulsion.x.temperature and we also have propulsion.x.oilTemp when it should be oilTemperature.

OK looks like an iKommunicate bug, will get this sorted.

**Comment by sumps** [comment]
However, the Batteries temperature issue is a different "kettle of fish". It looks like a whole series of keys have been added for battery temperature alarm limits. These surely are metadata and not measured values ? I think this has got messed up at some fairly recent point, as I am sure it has not always been like this.

The measured value is the battery temperature and this should be electrical.batteries.x.temperature which is what iKommunicate is outputting.

I think this needs fixing in the schema.

**Comment by tkurki** [comment]
The telltale is the missing unit (in your picture): then IP can not find the unit from the schema and will just show the value as it is.

**Comment by tkurki** [comment]
Yes, I noticed also that the limits that should be in metadata are messed up as data keys.

They should be like https://github.com/SignalK/specification/blob/master/schemas/groups/electrical.json#L65-L74

but are 
https://github.com/SignalK/specification/blob/master/schemas/groups/electrical.json#L147-L151

**Comment by tkurki** [comment]
Closing as out of date.
