### ISSUE TITLE
Consistent display of source

### ISSUE THREAD

**Issue by sumps** [SignalK/instrumentpanel#51]
Really like the smaller source text, as it is important when setting everything up but after that of little interest, so making it smaller is good.

However, the Position Gauge, which is probably going to be one of the most common gauges to have multiple sources is still displayed in larger text.

Also some of the gauges like the Wind and Reading gauges do not show source.

**Comment by tkurki** [comment]
Wind gauge source handling is another story, since it is a single gauge that displays data from more than one source.
