### ISSUE TITLE
UI should allow optional units for propulsion.port.fuel.rate

### ISSUE THREAD

**Issue by aplathan** [SignalK/instrumentpanel#56]
Currently only m3/s is available for propulsion.port.fuel.rate. Because the real life unit is so small, it gets rounded up to 0.00, and is useless. Users should be able to choose commonly used units such as L/h the same way temperatures allow K, C, F and so on.

**Comment by tkurki** [comment]
This should be fixe in master now. Let me know if you run into problems.

**Comment by aplathan** [comment]
Not sure if the fix is in master. I can't get the updated files with npm install signalk/instrumentpanel. Apologies in advance if I'm doing yet another rookie mistake with npm.

**Comment by tkurki** [comment]
My mistake, committed to wrong branch. Will fix later...

**Comment by tkurki** [comment]
Now it hopefully works. The latest version is deployed at http://node-master.signalk.org/instrumentpanel/ , you can try it out from there and connect to your server that has relevant data items.
