### ISSUE TITLE
Does not like Hostnames in URL

### ISSUE THREAD

**Issue by sumps** [SignalK/instrumentpanel#84]
If I use the hostname in the URL to access Node Server and Instrument Panel i.e. https://raspberrypi.local then Instrument Panel never connects. If however I use the IP address https://192.168.2.130 everything is fine.

I am running the latest Node Server and Instrument Panel, have security HTTPS turned ON and said YES to change the HTTP port from 3000 to 80 in the Config program.

**Comment by tkurki** [comment]
InstrumentPanel stores the address of the last SK server it connected to. This is stored in LocalSetttings, which specific to the hostname that was used to load InstrumentPanel.

In Paul's setup the IP loaded from https://raspberrypi.local/ was trying to connect to an ip address where there is no SK server any more.
